### ISSUE TITLE
Trigger Build Button returns 405

### ISSUE THREAD

**Issue by freshp** [mohamicorp/stash-jenkins-postreceive-webhook#116]
I use Stash and Jenkins. Now I try to get the "Stash Webhook to Jenkins" to work. The configuration check of the repository results "Success!". 

With the following Url I get the right jobs from jenkins http://jenkins.com/git/notifyCommit?url=ssh%3A%2F%2FmyRepository.git. 

The whole configuration looks right. But I get a "405 - Method Not Allowed" from the URL: 
http://stash.com/rest/jenkins/latest/projects/projectName/repos/repoName/triggerJenkins?branch=branchName&sha1=sha1 
This URL will be called by Trigger Build Button.

What can i do, to trigger the jobs from stash?

**Comment by janmaennig** [comment]
+1

**Comment by mikesir87** [comment]
Hmm... I'll take a look at this.  I'm assuming that the 405 you're seeing is from your Stash instance, not the Jenkins instance, correct?

Another question... are you logged in as a Stash admin when seeing this, or a normal user?

**Comment by freshp** [comment]
The 405 I still get, is from the Stash instance. I edited my issue.

I tested it as admin and as normal user.

**Comment by ashnazg** [comment]
I'm also seeing this behavior now, from the Trigger Build button on a PR, though *not* from the Trigger Jenkins button in the hook config.  I've verified the same behavior on the Trigger Build button from a PR (405 from Apache), as well as the manual notifyCommit URL just passing the repo URL (good result of "scheduled polling" in Jenkins log).

**Comment by ashnazg** [comment]
Is the 405 due to that Trigger Build button doing a POST, but hitting just the URL as if it was a GET isn't allowed?

**Comment by freshp** [comment]
I still try to call the same URL with parameter sha1 and branch as POST, but there is still an error. Its a 415 instead of 405, but an error.

**Comment by ashnazg** [comment]
I eventually figured out that the URL being constructed by the PR's Trigger Build button uses the attribute "branch" rather than "branches", and the latter does work properly.  I've sent a patch in (https://github.com/Nerdwin15/stash-jenkins-postreceive-webhook/pull/122).

**Comment by freshp** [comment]
sounds good! I tried it too, but with the same result, like before.

**Comment by ashnazg** [comment]
I tested out all the combinations of `url&branches&sha1` query params, **using a POST via Curl**, and they all succeed in triggering job polling.

Now, when testing just the raw URL itself in a browser (presumably a GET), the *only* thing that works is using `url` alone.  None of the other combinations result in triggered polling.  Some result in a good response of "No Git Jobs", some result in Jenkins stack trace errors (these indicate that `url` alone is absolutely required to always be included), and one combination that will trigger builds unrelated to the sha1 value and thus result in errors during the build (because the commit can't be found in the build's tracked branch).

So, the only working way to use the URL in a browser is the pass *only* the `url`.  Using Curl to send a POST, however, shows me that every possible combination of the three args is acceptable and works correctly to trigger SCM polling.

**Comment by ashnazg** [comment]
Rereading the OP, I may be speaking with some ambiguity.  The URLs I've tested are *only* the URLs hitting Jenkins, not any that hit Stash itself.  I've been debugging why PRs Stash have not been notifying Jenkins of their open and update state changes.

**Comment by ashnazg** [comment]
Hitting the Stash-targeted URL directly gives me 405s no matter what combination of args I give it.  I take this to mean the URL insists on a POST rather than a GET.

**Comment by ashnazg** [comment]
Wait, no... all those POSTs I was doing with Curl were indeed hitting my Stash server, not Jenkins...
